### PR TITLE
Update readme with quickstart step for grunt install.

### PR DESCRIPTION
**Pull request by jamesearl**
`npm install` fails if grunt is not present.

### CODE REVIEW

**Comment by rtgibbons** [comment]
What is the failure? Just a quick glance and I'm not seeing where it should?

Also, `grunt` shouldn't be installed globally; just `grunt-cli`.

**Comment by rtgibbons** [comment]
I see it, on https://github.com/cpbtechnology/boilerplate-frontend/blob/master/package.json#L5

    "postinstall": "export PATH=bin:$PATH && bower install && bundle install --binstubs && grunt githooks"

This is post install; so grunt is already there; But grunt does require `grunt-cli` to execute properly ... Probably just need to add `grunt-cli` to the package.json

**Comment by rtgibbons** [comment]
Bundler and Grunt are listed as requirements; But aren't listed under quick-start. Maybe we should list a common way to install Grunt and Bunlder, which requires Node and Ruby to be installed ... how deep down the rabbit hole do we go?

**Comment by bmsterling** [comment]
Good question, how far down the rabbit hole do we go.  I think we should add and I'll make that change.

**Comment by bmsterling** [comment]
Made the change locally but compass no longer likes something in the css code.  I'll push up the fix when time permits.

**Comment by ratherironic** [comment]
@bmsterling Hey Ben! Sorry for interrupting the thread, former CP+B dev here. I'm not sure if this is the issue you are running into but I noticed @import 'normalize-scss/_normalize'; and @import 'extra-strength-responsive-grids/css/_grid.generator'; are included in app.scss but those css libs don't exist within the boilerplate. Meant to create a git issue about this but it might be covered here if indeed that is the issue you are having. Cheers!

**Comment by bmsterling** [comment]
@ratherironic Thanks for the heads up, those two are now being pulled in view bower, [see here](https://github.com/cpbtechnology/boilerplate-frontend/blob/master/build/config/compass.js#L18).  My problem has to do with [these lines of code](https://github.com/cpbtechnology/boilerplate-frontend/blob/master/source/css/app/_00._global.scss#L5).  I'll be digging around to see why that is now an issue with the most recent compass.

**Pull request merged**
